### ISSUE TITLE
Filter parameter for /latest 

### ISSUE THREAD

**Issue by chaosblog** [Laeyoung/Wuhan-Coronavirus-API#6]
Would it be possible to add an filter to the API when querying /latest to get only the data of a specific country?
Something like /latest?iso2=US or /latest?iso3=USA to get only the US-records.

**Comment by espipj** [comment]
Hey @Laeyoung I think this issue, and #5 can be solved adding a parameter on the routes kind of like
`?onlyCountries=true` and making the sum of all the cities in those countries (China, US...) and returning the Country instead of by city, for the other countries we already have the data, so it would be easy I think. I can work on that if you want 😄

**Comment by Laeyoung** [comment]
Hi @chaosblog.

I just added filter by country iso feature.
Plz check this https://github.com/Laeyoung/COVID-19-API#latest

**Comment by Laeyoung** [comment]
Hello, @espipj 

Thank you for your opinion. In new release version, `?onlyCountries=true` param has been added.
You can test it at [this link](https://wuhan-coronavirus-api.laeyoung.endpoint.ainize.ai/jhu-edu/latest?iso2=US&onlyCountries=true)

**Comment by chaosblog** [comment]
@Laeyoung Thank you very much. Works like a charm.
